# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Builds

on:
  # Push to any tracked branches
  push:
    branches: [main]
  # PRs only on main branch
  pull_request:
    branches: [main]
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for build'
        required: true

jobs:
  build:
    name: Ferdium Recipes Build
    runs-on: ubuntu-20.04
    steps:
      - name: Print latest commit
        run: echo ${{ github.sha }}
      - name: Set env vars
        run: echo "PNPM_CACHE=$HOME/.pnpm-store" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js specified in the '.nvmrc' file
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install pnpm
        run: npm i -gf "pnpm@$(node -p 'require("./package.json").engines.pnpm')" && pnpm -v
      - name: Install node dependencies recursively
        run: pnpm i && pnpm lint && pnpm reformat-files && pnpm package
